server:
  port: 8093
spring.datasource:
  url: 'jdbc:postgresql://localhost:5432/postgres'
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
  hikari:
    data-source-properties:
      reWriteBatchedInserts: true
      hikari:
        maximumPoolSize: 20
        idleTimeout: 30000
        connectionTimeout: 20000
        poolName: test-pool
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
          useLocalSessionState: true
          rewriteBatchedStatements: true
          cacheResultSetMetadata: true
          cacheServerConfiguration: true